name: Sync Repository

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync Repository
        run: |
          git remote add upstream https://github.com/qbox/titan
          git pull upstream main
